spring :
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/micro_products
    username: root
    password: kien1610
  data :
    redis :
      host : localhost
      port : 6379
    cache  :
      type : redis
      redis :
        time-to-live : 600000 # thời gian sống của cache (ms)
  kafka :
    bootstrap-servers: localhost:9092
    consumer:
      group-id: product-service # tên nhóm consumer, các consumer cùng nhóm sẽ chia sẻ việc đọc dữ liệu từ topic
      auto-offset-reset: latest # nếu không có offset nào được lưu trữ - hay được hiểu là lần đầu đăng ký kafka, bắt đầu đọc từ cuối cùng của topic
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer # chuyển byte thành String khi nhận được từ kafka
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer # chuyển byte thành String khi nhận được từ kafka sau đó tự parse
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # chuyển String thành byte để gửi đi kafka
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # chuyển Json thành byte để gửi đi kafka
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL của Eureka Server

logging :
  level:
    org.springframework.cache : trace
    com.github.benmanes.caffeine : debug
    org.springframework.data.redis : debug
